DEFINE MOD number mod_num
	NEW current
	PUT current VARIABLE number
	WHILE GREATER VARIABLE current SUBTRACT VARIABLE mod_num 1
		PUT current SUBTRACT VARIABLE current VARIABLE mod_num
	END
	RETURN VARIABLE current
END
OUTPUT MOD 17 5